module.exports = {
	nodeRules: {
		'n/file-extension-in-import': [0],
		'n/no-deprecated-api': [2],
		'n/no-mixed-requires': [2, {grouping: true, allowCall: true}],
		'n/no-new-require': [2],
		'n/no-path-concat': [2],
		'n/no-unpublished-bin': [2],
		'n/prefer-global/buffer': [0],
		'n/prefer-global/console': [2, 'always'],
		'n/prefer-global/process': [0],
		'n/prefer-global/text-decoder': [2, 'always'],
		'n/prefer-global/text-encoder': [2, 'always'],
		'n/prefer-global/url': [2, 'always'],
		'n/prefer-global/url-search-params': [2, 'always'],
		'n/prefer-promises/dns': [2],
		'n/prefer-promises/fs': [2],
		'n/process-exit-as-throw': [2],
		'n/handle-callback-err': ['error', '^(err|error)$'],
		'n/no-exports-assign': 'error',
	},
};
