module.exports = {
	shopifyRules: {
		'@shopify/binary-assignment-parens': [0, 'always'],
		'@shopify/class-property-semi': [0],
		'@shopify/images-no-direct-imports': [0],
		'@shopify/no-ancestor-directory-import': [0],
		'@shopify/no-debugger': [2],
		'@shopify/no-fully-static-classes': [0],
		'@shopify/no-namespace-imports': [0],
		'@shopify/no-useless-computed-properties': [2],
		'@shopify/prefer-class-properties': [0],
		'@shopify/prefer-early-return': [2, {maximumStatements: 1}],
		'@shopify/prefer-module-scope-constants': [2],
		'@shopify/prefer-twine': [2],
		'@shopify/react-hooks-strict-return': [2],
		'@shopify/react-initialize-state': [2],
		'@shopify/react-no-multiple-render-methods': [2],
		'@shopify/react-prefer-private-members': [2],
		'@shopify/react-require-autocomplete': [2],
		'@shopify/react-type-state': [2],
		'@shopify/restrict-full-import': [0],
		'@shopify/sinon-no-restricted-features': [0],
		'@shopify/sinon-prefer-meaningful-assertions': [0],
		'@shopify/strict-component-boundaries': [0],
		'@shopify/typescript/prefer-build-client-schema': [2],
		'@shopify/typescript/prefer-pascal-case-enums': [2],
		'@shopify/typescript/prefer-singular-enums': [2],
		'@shopify/webpack/no-unnamed-dynamic-imports': [0],
	},
};
