version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 99
    reviewers:
      - 'pnodet'

  - package-ecosystem: npm
    directory: '/'
    open-pull-requests-limit: 20
    versioning-strategy: increase
    reviewers:
      - 'pnodet'
    schedule:
      interval: daily
      time: '09:00'
      timezone: 'Europe/Paris'
    ignore:
      # Manually update major versions of @types/node with the version specified within .nvmrc
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']
