/* eslint-disable max-lines */
import globals from 'globals';
import {pluginUnusedImports} from '../plugins';
import {isInEditor} from '../env';
import type {FlatESLintConfigItem} from 'eslint-define-config';

const MAX_COMPLEXITY = 20;
const DEFAULT_IDENTATION = 2;
const MAX_CLASSES_PER_FILE = 1;
const MAX_DEPTH = 4;
const MAX_LENGTH = 80;
const MAX_NESTED_CALLBACKS = 3;
const MAX_PARAMS = 5;
const MAX_STATEMENTS = 30;

export const javascript: FlatESLintConfigItem[] = [
	{
		languageOptions: {
			globals: {
				...globals.browser,
				...globals.es2021,
				...globals.node,
			},
			parserOptions: {
				ecmaFeatures: {
					jsx: true,
				},
				sourceType: 'module',
			},
			sourceType: 'module',
		},
		plugins: {
			'unused-imports': pluginUnusedImports,
		},
		rules: {
			'block-scoped-var': 'error',
			'constructor-super': 'error',
			eqeqeq: ['error', 'smart'],
			'for-direction': 'error',
			'getter-return': ['error', {allowImplicit: true}],
			'no-alert': 'warn',
			'no-async-promise-executor': 'error',
			'no-case-declarations': 'error',
			'no-class-assign': 'error',
			'no-compare-neg-zero': 'error',
			'no-cond-assign': ['error', 'always'],
			'no-console': ['warn', {allow: ['warn', 'error', 'info']}],
			'no-const-assign': 'error',
			'no-constant-condition': ['error', {checkLoops: false}],
			'no-control-regex': 'error',
			'no-debugger': 'warn',
			'no-delete-var': 'error',
			'no-dupe-args': 'error',
			'no-dupe-class-members': 'error',
			'no-dupe-else-if': 'error',
			'no-dupe-keys': 'error',
			'no-duplicate-case': 'error',
			'no-duplicate-imports': 'error',
			'no-empty': ['error', {allowEmptyCatch: true}],
			'no-empty-character-class': 'error',
			'no-empty-pattern': 'error',
			'no-ex-assign': 'error',
			'no-extra-boolean-cast': 'error',
			'no-fallthrough': ['warn', {commentPattern: 'break[\\s\\w]*omitted'}],
			'no-func-assign': 'error',
			'no-global-assign': ['error', {exceptions: []}],
			'no-import-assign': 'error',
			'no-inner-declarations': ['error', 'functions'],
			'no-invalid-regexp': ['error', {allowConstructorFlags: ['u', 'y']}],
			'no-irregular-whitespace': 'error',
			'no-lonely-if': 'error',
			'no-loss-of-precision': 'error',
			'no-misleading-character-class': 'error',
			'no-mixed-spaces-and-tabs': 'error',
			'no-multi-str': 'error',
			'no-new-symbol': 'error',
			'no-nonoctal-decimal-escape': 'error',
			'no-obj-calls': 'error',
			'no-octal': 'error',
			'no-prototype-builtins': 'error',
			'no-redeclare': 'error',
			'no-regex-spaces': 'error',
			'no-return-await': 'warn',
			'no-self-assign': ['error', {props: true}],
			'no-setter-return': 'error',
			'no-shadow-restricted-names': 'error',
			'no-sparse-arrays': 'error',
			'no-this-before-super': 'error',
			'no-undef': 'error',
			'no-unexpected-multiline': 'error',
			'no-unreachable': 'error',
			'no-unsafe-finally': 'error',
			'no-unsafe-negation': ['error', {enforceForOrderingRelations: true}],
			'no-unsafe-optional-chaining': [
				'error',
				{disallowArithmeticOperators: true},
			],
			'no-unused-expressions': [
				'error',
				{
					allowShortCircuit: true,
					allowTaggedTemplates: true,
					allowTernary: true,
				},
			],
			'no-unused-labels': 'error',
			'no-unused-vars': 'off',
			'no-useless-backreference': 'error',
			'no-useless-catch': 'error',
			'no-useless-escape': 'error',
			'no-void': 'error',
			'no-with': 'error',
			'object-shorthand': [
				'error',
				'always',
				{avoidQuotes: true, ignoreConstructors: false},
			],
			'prefer-arrow-callback': [
				'error',
				{allowNamedFunctions: false, allowUnboundThis: true},
			],
			'prefer-const': [
				'warn',
				{destructuring: 'all', ignoreReadBeforeAssign: true},
			],
			'prefer-exponentiation-operator': 'error',
			'prefer-regex-literals': ['error', {disallowRedundantWrapping: true}],
			'prefer-rest-params': 'error',
			'prefer-spread': 'error',
			'prefer-template': 'error',
			'require-await': 'error',
			'require-yield': 'error',
			'sort-imports': [
				'error',
				{
					allowSeparatedGroups: false,
					ignoreCase: false,
					ignoreDeclarationSort: true,
					ignoreMemberSort: false,
					memberSyntaxSortOrder: ['none', 'all', 'multiple', 'single'],
				},
			],
			'unicode-bom': ['error', 'never'],
			'unused-imports/no-unused-imports': isInEditor ? 'off' : 'error',
			'unused-imports/no-unused-vars': [
				'error',
				{args: 'after-used', ignoreRestSiblings: true},
			],
			'use-isnan': [
				'error',
				{enforceForIndexOf: true, enforceForSwitchCase: true},
			],
			'valid-typeof': ['error', {requireStringLiterals: true}],
			'vars-on-top': 'error',
			'wrap-iife': ['error', 'outside', {functionPrototypeMethods: true}],
			'accessor-pairs': [
				'error',
				{
					getWithoutSet: false,
					setWithoutGet: true,
					enforceForClassMembers: true,
				},
			],
			'array-bracket-newline': ['off', 'consistent'],
			'array-bracket-spacing': ['off', 'never'],
			'array-callback-return': [
				'error',
				{allowImplicit: true, checkForEach: false},
			],
			'array-element-newline': ['off', {multiline: true, minItems: 3}],
			'arrow-body-style': ['error', 'as-needed'],
			'arrow-parens': ['off', 'always'],
			'arrow-spacing': ['off', {before: true, after: true}],
			'block-spacing': ['off', 'always'],
			'brace-style': ['off', '1tbs', {allowSingleLine: true}],
			'callback-return': ['error', ['callback']],
			camelcase: [
				'error',
				{
					properties: 'never',
					ignoreDestructuring: false,
					ignoreImports: false,
					ignoreGlobals: true,
				},
			],
			'capitalized-comments': [
				'off',
				'never',
				{
					line: {
						ignorePattern: '.*',
						ignoreInlineComments: true,
						ignoreConsecutiveComments: true,
					},
					block: {
						ignorePattern: '.*',
						ignoreInlineComments: true,
						ignoreConsecutiveComments: true,
					},
				},
			],
			'class-methods-use-this': [
				'error',
				{exceptMethods: [], enforceForClassFields: true},
			],
			'comma-dangle': [
				'off',
				{
					arrays: 'always-multiline',
					objects: 'always-multiline',
					imports: 'always-multiline',
					exports: 'always-multiline',
					functions: 'always-multiline',
				},
			],
			'comma-spacing': ['off', {before: false, after: true}],
			'comma-style': ['off', 'last'],
			complexity: ['error', MAX_COMPLEXITY],
			'computed-property-spacing': ['off', 'never'],
			'consistent-return': ['off'],
			'consistent-this': ['off', 'that'],
			curly: ['off', 'all'],
			'default-case': ['error', {commentPattern: '(?:)'}],
			'default-case-last': ['error'],
			'default-param-last': ['off'],
			'dot-location': ['error', 'property'],
			'dot-notation': ['warn', {allowKeywords: true, allowPattern: ''}],
			'eol-last': ['error', 'always'],
			'flowtype/boolean-style': ['off'],
			'flowtype/delimiter-dangle': ['off'],
			'flowtype/generic-spacing': ['off'],
			'flowtype/object-type-curly-spacing': ['off'],
			'flowtype/object-type-delimiter': ['off'],
			'flowtype/quotes': ['off'],
			'flowtype/semi': ['off'],
			'flowtype/space-after-type-colon': ['off'],
			'flowtype/space-before-generic-bracket': ['off'],
			'flowtype/space-before-type-colon': ['off'],
			'flowtype/union-intersection-spacing': ['off'],
			'func-call-spacing': ['off', 'never'],
			'func-name-matching': [
				'error',
				'never',
				{includeCommonJSModuleExports: false, considerPropertyDescriptor: true},
			],
			'func-names': ['warn'],
			'func-style': ['error', 'expression', {allowArrowFunctions: true}],
			'function-call-argument-newline': ['off', 'consistent'],
			'function-paren-newline': ['off', 'consistent'],
			'generator-star': ['off'],
			'generator-star-spacing': ['off', 'after'],
			'global-require': ['off'],
			'grouped-accessor-pairs': ['error', 'getBeforeSet'],
			'guard-for-in': ['off'],
			'handle-callback-err': ['off'],
			'id-blacklist': ['off'],
			'id-denylist': ['error', 'native'],
			'id-length': [
				'error',
				{
					min: 2,
					max: 30,
					properties: 'never',
					exceptions: ['_', 'i', 'j', 'k', 'x', 'y', 'z'],
				},
			],
			'id-match': ['off'],
			'implicit-arrow-linebreak': ['off', 'beside'],
			indent: [
				'off',
				DEFAULT_IDENTATION,
				{
					SwitchCase: 1,
					VariableDeclarator: 1,
					outerIIFEBody: 1,
					FunctionDeclaration: {
						parameters: 1,
						body: 1,
					},
					FunctionExpression: {
						parameters: 1,
						body: 1,
					},
					CallExpression: {
						arguments: 1,
					},
					ArrayExpression: 1,
					ObjectExpression: 1,
					ImportDeclaration: 1,
					flatTernaryExpressions: false,
					ignoredNodes: [
						'JSXElement',
						'JSXElement > *',
						'JSXAttribute',
						'JSXIdentifier',
						'JSXNamespacedName',
						'JSXMemberExpression',
						'JSXSpreadAttribute',
						'JSXExpressionContainer',
						'JSXOpeningElement',
						'JSXClosingElement',
						'JSXFragment',
						'JSXOpeningFragment',
						'JSXClosingFragment',
						'JSXText',
						'JSXEmptyExpression',
						'JSXSpreadChild',
					],
					ignoreComments: false,
					offsetTernaryExpressions: false,
				},
			],
			'indent-legacy': [
				'off',
				DEFAULT_IDENTATION,
				{SwitchCase: 1, MemberExpression: 1},
			],
			'init-declarations': ['off', 'always'],
			'key-spacing': ['off', {beforeColon: false, afterColon: true}],
			'keyword-spacing': ['off', {before: true, after: true, overrides: {}}],
			'line-comment-position': ['off', {position: 'above'}],
			'linebreak-style': ['off', 'unix'],
			'lines-around-comment': [
				'off',
				{
					beforeBlockComment: true,
					afterBlockComment: false,
					beforeLineComment: false,
					afterLineComment: false,
					allowBlockStart: false,
					allowBlockEnd: false,
				},
			],
			'lines-around-directive': ['error', {before: 'always', after: 'always'}],
			'lines-between-class-members': [
				'off',
				'always',
				{exceptAfterSingleLine: true},
			],
			'max-classes-per-file': ['off', MAX_CLASSES_PER_FILE],
			'max-depth': ['error', MAX_DEPTH],
			'max-len': [
				'error',
				MAX_LENGTH,
				DEFAULT_IDENTATION,
				{
					ignoreUrls: true,
					ignoreComments: true,
					ignoreRegExpLiterals: true,
					ignoreStrings: true,
					ignoreTemplateLiterals: true,
				},
			],
			'max-lines': [
				'error',
				{
					max: 350,
					skipBlankLines: true,
					skipComments: true,
				},
			],
			'max-lines-per-function': [
				'error',
				{
					max: 100,
					skipBlankLines: true,
					skipComments: true,
					IIFEs: true,
				},
			],
			'max-nested-callbacks': ['error', MAX_NESTED_CALLBACKS],
			'max-params': ['error', MAX_PARAMS],
			'max-statements': ['error', MAX_STATEMENTS],
			'max-statements-per-line': ['error', {max: 1}],
			'multiline-comment-style': ['warn', 'bare-block'],
			'multiline-ternary': ['off', 'always-multiline'],
			'new-cap': [
				'warn',
				{
					newIsCap: true,
					capIsNew: false,
					properties: true,
				},
			],
			'new-parens': ['error'],
			'newline-after-var': ['off'],
			'newline-before-return': ['off'],
			'newline-per-chained-call': ['off', {ignoreChainWithDepth: 3}],
			'no-array-constructor': ['error'],
			'no-arrow-condition': ['off'],
			'no-await-in-loop': ['error'],
			'no-bitwise': ['off'],
			'no-buffer-constructor': ['error'],
			'no-caller': ['error'],
			'no-catch-shadow': ['error'],
			'no-comma-dangle': ['off'],
			'no-confusing-arrow': [
				'off',
				{allowParens: true, onlyOneSimpleParam: false},
			],
			'no-constructor-return': ['error'],
			'no-continue': ['off'],
			'no-div-regex': ['error'],
			'no-else-return': ['error', {allowElseIf: false}],
			'no-empty-function': ['error', {allow: ['arrowFunctions', 'functions']}],
			'no-eq-null': ['off'],
			'no-eval': ['error'],
			'no-extend-native': ['error'],
			'no-extra-bind': ['error'],
			'no-extra-label': ['error'],
			'no-extra-parens': [
				'off',
				'all',
				{
					conditionalAssign: true,
					nestedBinaryExpressions: false,
					returnAssign: false,
					ignoreJSX: 'all',
					enforceForArrowConditionals: false,
				},
			],
			'no-extra-semi': ['error'],
			'no-floating-decimal': ['error'],
			'no-implicit-coercion': [
				'error',
				{
					'boolean': false,
					number: true,
					string: true,
					disallowTemplateShorthand: false,
					allow: [],
				},
			],
			'no-implicit-globals': ['error'],
			'no-implied-eval': ['error'],
			'no-inline-comments': ['off'],
			'no-invalid-this': ['error'],
			'no-iterator': ['error'],
			'no-label-var': ['error'],
			'no-labels': [
				'error',
				{
					allowLoop: false,
					allowSwitch: false,
				},
			],
			'no-lone-blocks': ['error'],
			'no-loop-func': ['error'],
			'no-magic-numbers': [
				'warn',
				{
					ignore: [],
					ignoreArrayIndexes: true,
					enforceConst: true,
					detectObjects: false,
				},
			],
			'no-mixed-operators': [
				'error',
				{
					groups: [
						['%', '**'],
						['%', '+'],
						['%', '-'],
						['%', '*'],
						['%', '/'],
						['/', '*'],
						['&', '|', '<<', '>>', '>>>'],
						['==', '!=', '===', '!=='],
						['&&', '||'],
					],
					allowSamePrecedence: true,
				},
			],
			'no-mixed-requires': ['off', false],
			'no-multi-assign': ['error', {ignoreNonDeclaration: false}],
			'no-multi-spaces': ['error', {ignoreEOLComments: false}],
			'no-multiple-empty-lines': ['error', {max: 1, maxEOF: 1}],
			'no-native-reassign': ['off'],
			'no-negated-condition': ['error'],
			'no-negated-in-lhs': ['off'],
			'no-nested-ternary': ['off'],
			'no-new': ['error'],
			'no-new-func': ['error'],
			'no-new-object': ['error'],
			'no-new-require': ['off'],
			'no-new-wrappers': ['error'],
			'no-octal-escape': ['error'],
			'no-param-reassign': [
				'error',
				{
					props: true,
					ignorePropertyModificationsFor: [],
					ignorePropertyModificationsForRegex: [],
				},
			],
			'no-path-concat': ['error'],
			'no-plusplus': ['error', {allowForLoopAfterthoughts: true}],
			'no-process-env': ['error'],
			'no-process-exit': ['error'],
			'no-promise-executor-return': ['error'],
			'no-proto': ['error'],
			'no-reserved-keys': ['off'],
			'no-restricted-exports': ['error', {restrictedNamedExports: ['then']}],
			'no-restricted-globals': [
				'off',
				{
					name: 'isFinite',
					message:
						'Use Number.isFinite instead https://github.com/airbnb/javascript#standard-library--isfinite',
				},
				{
					name: 'isNaN',
					message:
						'Use Number.isNaN instead https://github.com/airbnb/javascript#standard-library--isnan',
				},
				'addEventListener',
				'blur',
				'close',
				'closed',
				'confirm',
				'defaultStatus',
				'defaultstatus',
				'event',
				'external',
				'find',
				'focus',
				'frameElement',
				'frames',
				'history',
				'innerHeight',
				'innerWidth',
				'length',
				'location',
				'locationbar',
				'menubar',
				'moveBy',
				'moveTo',
				'name',
				'onblur',
				'onerror',
				'onfocus',
				'onload',
				'onresize',
				'onunload',
				'open',
				'opener',
				'opera',
				'outerHeight',
				'outerWidth',
				'pageXOffset',
				'pageYOffset',
				'parent',
				'print',
				'removeEventListener',
				'resizeBy',
				'resizeTo',
				'screen',
				'screenLeft',
				'screenTop',
				'screenX',
				'screenY',
				'scroll',
				'scrollbars',
				'scrollBy',
				'scrollTo',
				'scrollX',
				'scrollY',
				'self',
				'status',
				'statusbar',
				'stop',
				'toolbar',
				'top',
			],
			'no-restricted-imports': ['off', {paths: [], patterns: []}],
			'no-restricted-modules': ['off'],
			'no-restricted-properties': [
				'error',
				{
					object: 'Symbol',
					property: 'for',
					message: 'Symbol.for is unshimmable',
				},
				{
					object: 'arguments',
					property: 'callee',
					message: 'arguments.callee is deprecated',
				},
				{
					property: '__defineGetter__',
					message: 'Please use Object.defineProperty instead.',
				},
				{
					property: '__defineSetter__',
					message: 'Please use Object.defineProperty instead.',
				},
			],
			'no-restricted-syntax': [
				'error',
				'DebuggerStatement',
				{
					selector: 'ForInStatement',
					message:
						'for..in loops iterate over the entire prototype chain, which is virtually never what you want. Use Object.{keys,values,entries}, and iterate over the resulting array.',
				},
				{
					selector: 'LabeledStatement',
					message:
						'Labels are a form of GOTO; using them makes code confusing and hard to maintain and understand.',
				},
				{
					selector: 'WithStatement',
					message:
						'`with` is disallowed in strict mode because it makes code impossible to predict and optimize.',
				},
				{
					selector: ':matches(ImportNamespaceSpecifier)',
					message: 'Import/export only modules you need',
				},
			],
			'no-return-assign': ['error', 'always'],
			'no-script-url': ['error'],
			'no-self-compare': ['off'],
			'no-sequences': ['error', {allowInParentheses: false}],
			'no-shadow': ['off'],
			'no-space-before-semi': ['off'],
			'no-spaced-func': ['off'],
			'no-sync': ['off'],
			'no-tabs': ['off'],
			'no-template-curly-in-string': ['error'],
			'no-ternary': ['off'],
			'no-throw-literal': ['error'],
			'no-trailing-spaces': [
				'error',
				{
					skipBlankLines: false,
					ignoreComments: false,
				},
			],
			'no-undef-init': ['error'],
			'no-undefined': ['error'],
			'no-underscore-dangle': [
				'off',
				{
					allow: ['__REDUX_DEVTOOLS_EXTENSION_COMPOSE__'],
					allowAfterThis: false,
					allowAfterSuper: false,
					enforceInMethodNames: true,
					allowAfterThisConstructor: false,
					allowFunctionParams: true,
					enforceInClassFields: false,
				},
			],
			'no-unmodified-loop-condition': ['error'],
			'no-unneeded-ternary': ['error', {defaultAssignment: false}],
			'no-unreachable-loop': ['error', {ignore: []}],
			'no-unused-private-class-members': ['error'],
			'no-use-before-define': ['error', 'nofunc'],
			'no-useless-call': ['error'],
			'no-useless-computed-key': ['error', {enforceForClassMembers: true}],
			'no-useless-concat': ['error'],
			'no-useless-constructor': ['error'],
			'no-useless-rename': [
				'error',
				{
					ignoreDestructuring: false,
					ignoreImport: false,
					ignoreExport: false,
				},
			],
			'no-useless-return': ['error'],
			'no-var': ['error'],
			'no-warning-comments': ['warn', {terms: ['fixme', 'todo']}],
			'no-whitespace-before-property': ['off'],
			'nonblock-statement-body-position': ['off', 'beside', {overrides: {}}],
			'object-curly-newline': [
				'off',
				{
					ObjectExpression: {
						minProperties: 4,
						multiline: true,
						consistent: true,
					},
					ObjectPattern: {
						minProperties: 4,
						multiline: true,
						consistent: true,
					},
					ImportDeclaration: {
						minProperties: 4,
						multiline: true,
						consistent: true,
					},
					ExportDeclaration: {
						minProperties: 4,
						multiline: true,
						consistent: true,
					},
				},
			],
			'object-curly-spacing': ['off', 'never'],
			'object-property-newline': [
				'off',
				{
					allowAllPropertiesOnSameLine: true,
					allowMultiplePropertiesPerLine: false,
				},
			],
			'one-var': ['off', 'never'],
			'one-var-declaration-per-line': ['error', 'initializations'],
			'operator-assignment': ['off', 'always'],
			'operator-linebreak': [
				'off',
				'after',
				{
					overrides: {
						'?': 'before',
						':': 'before',
					},
				},
			],
			'padded-blocks': [
				'off',
				{
					blocks: 'never',
					classes: 'never',
					switches: 'never',
				},
				{
					allowSingleLineBlocks: true,
				},
			],
			'padding-line-between-statements': [
				'off',
				{
					blankLine: 'always',
					prev: 'directive',
					next: '*',
				},
				{
					blankLine: 'any',
					prev: 'directive',
					next: 'directive',
				},
			],
			'prefer-destructuring': [
				'off',
				{
					VariableDeclarator: {
						array: false,
						object: true,
					},
					AssignmentExpression: {
						array: true,
						object: true,
					},
				},
				{
					enforceForRenamedProperties: false,
				},
			],
			'prefer-named-capture-group': ['off'],
			'prefer-numeric-literals': ['off'],
			'prefer-object-has-own': ['off'],
			'prefer-object-spread': ['off'],
			'prefer-promise-reject-errors': ['error', {allowEmptyReject: true}],
			'prefer-reflect': ['off'],
			'quote-props': ['error', 'as-needed', {keywords: true}],
			quotes: ['error', 'single', 'avoid-escape'],
			radix: ['error'],
			'require-atomic-updates': ['error', {allowProperties: true}],
			'require-jsdoc': ['off'],
			'require-unicode-regexp': ['off'],
			'rest-spread-spacing': ['error', 'never'],
			semi: ['error', 'always'],
			'semi-spacing': [
				'error',
				{
					before: false,
					after: true,
				},
			],
			'semi-style': ['error', 'last'],
			'sort-keys': [
				'off',
				'asc',
				{
					caseSensitive: false,
					natural: true,
				},
			],
			'sort-vars': ['off'],
			'space-after-function-name': ['off'],
			'space-after-keywords': ['off'],
			'space-before-blocks': ['off', 'always'],
			'space-before-function-paren': [
				'off',
				{
					anonymous: 'never',
					named: 'never',
					asyncArrow: 'always',
				},
			],
			'space-before-function-parentheses': ['off'],
			'space-before-keywords': ['off'],
			'space-in-brackets': ['off'],
			'space-in-parens': ['off', 'never'],
			'space-infix-ops': ['off'],
			'space-return-throw-case': ['off'],
			'space-unary-ops': [
				'off',
				{
					words: true,
					nonwords: false,
				},
			],
			'space-unary-word-ops': ['off'],
			'spaced-comment': [
				'error',
				'always',
				{
					markers: ['='],
				},
			],
			strict: ['error', 'global'],
			'switch-colon-spacing': [
				'off',
				{
					after: true,
					before: false,
				},
			],
			'symbol-description': ['error'],
			'template-curly-spacing': ['off', 'never'],
			'template-tag-spacing': ['off', 'never'],
			'valid-jsdoc': ['off'],
			'wrap-regex': ['off'],
			'yield-star-spacing': [
				'off',
				{
					before: false,
					after: true,
				},
			],
			yoda: [
				'error',
				'never',
				{
					exceptRange: true,
					onlyEquality: false,
				},
			],
		},
	},
	{
		files: ['**/scripts/*', '**/cli.*'],
		rules: {
			'no-console': 'off',
		},
	},
	{
		files: ['**/*.{test,spec}.js?(x)'],
		rules: {
			'no-unused-expressions': 'off',
		},
	},
];
