import {GLOB_REACT, GLOB_SRC, GLOB_TS, GLOB_TSX} from '../globs';
import {paddingLines} from '../lib/padding-lines';
import {pluginStylistic} from '../plugins';
import type {FlatESLintConfigItem} from 'eslint-define-config';

export const stylistic: FlatESLintConfigItem[] = [
	{
		plugins: {
			style: pluginStylistic,
		},
	},
	{
		files: [GLOB_SRC],
		rules: {
			'curly': ['error', 'multi', 'consistent'],

			'style/array-bracket-spacing': ['error', 'never'],
			'style/arrow-parens': ['off', 'as-needed', {requireForBlockBody: false}],
			'style/arrow-spacing': ['error', {after: true, before: true}],
			'style/block-spacing': ['error', 'never'],
			'style/brace-style': ['error', '1tbs', {allowSingleLine: true}],
			// handled by typescript-eslint
			'style/comma-dangle': ['off', 'always-multiline'],
			'style/comma-spacing': ['error', {after: true, before: false}],
			'style/comma-style': ['error', 'last'],
			'style/computed-property-spacing': [
				'error',
				'never',
				{enforceForClassMembers: true},
			],
			'style/dot-location': ['error', 'property'],
			'style/eol-last': 'error',
			'style/indent': ['off', 'tab'],
			'style/key-spacing': ['error', {afterColon: true, beforeColon: false}],
			'style/keyword-spacing': ['error', {after: true, before: true}],
			'style/lines-between-class-members': [
				'error',
				'always',
				{exceptAfterSingleLine: true},
			],
			'style/max-statements-per-line': ['error', {max: 1}],
			'style/member-delimiter-style': ['error'],
			'style/multiline-ternary': ['off', 'always-multiline'],
			'style/new-parens': 'error',
			'style/no-extra-parens': ['error', 'functions'],
			'style/no-extra-semi': ['error'],
			'style/no-floating-decimal': 'error',
			'style/no-mixed-operators': [
				'error',
				{
					allowSamePrecedence: true,
					groups: [
						['%', '**'],
						['%', '+'],
						['%', '-'],
						['%', '*'],
						['%', '/'],
						['/', '*'],
						['&', '|', '<<', '>>', '>>>'],
						['&&', '||'],
						['==', '!=', '===', '!=='],
						['==', '!=', '===', '!==', '>', '>=', '<', '<='],
						['&&', '||'],
						['in', 'instanceof'],
					],
				},
			],
			'style/no-mixed-spaces-and-tabs': 'off',
			'style/no-multi-spaces': ['error', {ignoreEOLComments: false}],
			'style/no-multiple-empty-lines': [
				'error',
				{max: 1, maxBOF: 0, maxEOF: 0},
			],
			'style/no-tabs': 'off',
			'style/no-trailing-spaces': [
				'off',
				{
					ignoreComments: true,
					skipBlankLines: true,
				},
			],
			'style/no-whitespace-before-property': 'error',
			'style/object-curly-spacing': ['error', 'never'],
			'style/one-var-declaration-per-line': ['error', 'initializations'],
			'style/operator-linebreak': [
				'error',
				'after',
				{
					overrides: {
						':': 'before',
						'?': 'before',
					},
				},
			],
			'style/padded-blocks': [
				'error',
				{blocks: 'never', classes: 'never', switches: 'never'},
			],
			'style/padding-line-between-statements': ['error', ...paddingLines],
			'style/quote-props': ['error', 'consistent-as-needed', {keywords: true}],
			'style/quotes': [
				'error',
				'single',
				{allowTemplateLiterals: true, avoidEscape: true},
			],
			'style/rest-spread-spacing': ['error', 'never'],
			'style/semi': ['error', 'always'],
			'style/semi-spacing': ['error', {after: true, before: false}],
			'style/semi-style': ['error', 'last'],
			'style/space-before-blocks': ['error', 'always'],
			'style/space-before-function-paren': [
				'error',
				{anonymous: 'always', asyncArrow: 'always', named: 'never'},
			],
			'style/space-in-parens': ['error', 'never'],
			'style/space-infix-ops': 'error',
			'style/space-unary-ops': ['error', {nonwords: false, words: true}],
			'style/spaced-comment': [
				'error',
				'always',
				{
					block: {
						balanced: true,
						exceptions: ['*'],
						markers: ['!'],
					},
					line: {
						exceptions: ['/', '#'],
						markers: ['/'],
					},
				},
			],
			'style/template-curly-spacing': 'error',
			'style/template-tag-spacing': ['error', 'never'],
			'style/type-annotation-spacing': ['error', {}],
			'style/wrap-iife': ['error', 'outside', {functionPrototypeMethods: true}],
			'style/yield-star-spacing': ['error', 'after'],
		},
	},
	{
		files: [GLOB_REACT],
		rules: {
			'style/jsx-closing-bracket-location': 'off',
			'style/jsx-closing-tag-location': 'off',
			'style/jsx-curly-brace-presence': [
				'error',
				{propElementValues: 'always'},
			],
			'style/jsx-curly-newline': 'off',
			'style/jsx-curly-spacing': ['error', 'never'],
			'style/jsx-equals-spacing': 'error',
			'style/jsx-first-prop-new-line': 'error',
			'style/jsx-indent': [
				'off',
				'tab',
				{checkAttributes: true, indentLogicalExpressions: true},
			],
			'style/jsx-indent-props': ['off', 'tab'],
			'style/jsx-max-props-per-line': [
				'error',
				{maximum: 1, when: 'multiline'},
			],
			'style/jsx-one-expression-per-line': ['off', {allow: 'single-child'}],
			'style/jsx-quotes': ['error', 'prefer-single'],
			'style/jsx-tag-spacing': [
				'error',
				{
					afterOpening: 'never',
					beforeClosing: 'never',
					beforeSelfClosing: 'always',
					closingSlash: 'never',
				},
			],
			'style/jsx-wrap-multilines': [
				'off',
				{
					arrow: 'parens-new-line',
					assignment: 'parens-new-line',
					condition: 'parens-new-line',
					declaration: 'parens-new-line',
					logical: 'parens-new-line',
					prop: 'parens-new-line',
					return: 'parens-new-line',
				},
			],
		},
	},
	{
		files: [GLOB_TS, GLOB_TSX],
		rules: {
			// overwritten by typescript-eslint
			'style/padding-line-between-statements': 'off',
		},
	},
	{
		files: [GLOB_SRC],
		// Rules disabled by Prettier normally
		rules: {
			'style/array-bracket-newline': 'off',
			'style/array-bracket-spacing': 'off',
			'style/array-element-newline': 'off',
			'style/arrow-parens': 'off',
			'style/arrow-spacing': 'off',
			'style/babel/object-curly-spacing': 'off',
			'style/babel/quotes': 'off',
			'style/babel/semi': 'off',
			'style/block-spacing': 'off',
			'style/brace-style': 'off',
			'style/comma-dangle': 'off',
			'style/comma-spacing': 'off',
			'style/comma-style': 'off',
			'style/computed-property-spacing': 'off',
			'style/curly': 'off',
			'style/dot-location': 'off',
			'style/eol-last': 'off',
			'style/func-call-spacing': 'off',
			'style/function-call-argument-newline': 'off',
			'style/function-paren-newline': 'off',
			'style/generator-star-spacing': 'off',
			'style/implicit-arrow-linebreak': 'off',
			'style/indent': 'off',
			'style/jsx-quotes': 'off',
			'style/key-spacing': 'off',
			'style/keyword-spacing': 'off',
			'style/linebreak-style': 'off',
			'style/lines-around-comment': 'off',
			'style/max-len': 'off',
			'style/max-statements-per-line': 'off',
			'style/multiline-ternary': 'off',
			'style/new-parens': 'off',
			'style/newline-per-chained-call': 'off',
			'style/no-confusing-arrow': 'off',
			'style/no-extra-parens': 'off',
			'style/no-extra-semi': 'off',
			'style/no-floating-decimal': 'off',
			'style/no-mixed-operators': 'off',
			'style/no-mixed-spaces-and-tabs': 'off',
			'style/no-multi-spaces': 'off',
			'style/no-multiple-empty-lines': 'off',
			'style/no-tabs': 'off',
			'style/no-trailing-spaces': 'off',
			'style/no-unexpected-multiline': 'off',
			'style/no-whitespace-before-property': 'off',
			'style/nonblock-statement-body-position': 'off',
			'style/object-curly-newline': 'off',
			'style/object-curly-spacing': 'off',
			'style/object-property-newline': 'off',
			'style/one-var-declaration-per-line': 'off',
			'style/operator-linebreak': 'off',
			'style/padded-blocks': 'off',
			'style/quote-props': 'off',
			'style/quotes': 'off',
			'style/rest-spread-spacing': 'off',
			'style/semi': 'off',
			'style/semi-spacing': 'off',
			'style/semi-style': 'off',
			'style/space-before-blocks': 'off',
			'style/space-before-function-paren': 'off',
			'style/space-in-parens': 'off',
			'style/space-infix-ops': 'off',
			'style/space-unary-ops': 'off',
			'style/standard/array-bracket-even-spacing': 'off',
			'style/standard/computed-property-even-spacing': 'off',
			'style/standard/object-curly-even-spacing': 'off',
			'style/switch-colon-spacing': 'off',
			'style/template-curly-spacing': 'off',
			'style/template-tag-spacing': 'off',
			'style/wrap-iife': 'off',
			'style/wrap-regex': 'off',
			'style/yield-star-spacing': 'off',
		},
	},
];
