/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable max-lines */
import js from '@eslint/js';
import type {Linter} from 'eslint';
import globals from 'globals';
import {
	DEFAULT_IGNORED_FILES,
	ECMA_VERSION,
	FILES,
	MOD_FILES,
} from '../constants.js';

export const coreConfig: Linter.FlatConfig[] = [
	{ignores: DEFAULT_IGNORED_FILES},
	{linterOptions: {reportUnusedDisableDirectives: true}},
	{
		files: FILES,
		...js.configs.recommended,
		languageOptions: {
			// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
			globals: {
				...globals['shared-node-browser'],
				...globals.browser,
				...globals.es6,
			},
			ecmaVersion: ECMA_VERSION,
			parserOptions: {
				ecmaVersion: ECMA_VERSION,
			},
		},
	},
	{
		files: MOD_FILES,
		languageOptions: {
			// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
			globals: {...globals.commonjs},
			parserOptions: {
				sourceType: 'module',
			},
		},
	},
	{
		files: FILES,
		rules: {
			'accessor-pairs': [
				'error',
				{
					getWithoutSet: false,
					setWithoutGet: true,
					enforceForClassMembers: true,
				},
			],
			'array-bracket-newline': ['off', 'consistent'],
			'array-bracket-spacing': ['off', 'never'],
			'array-callback-return': [
				'error',
				{allowImplicit: true, checkForEach: false},
			],
			'array-element-newline': ['off', {multiline: true, minItems: 3}],
			'arrow-body-style': ['error', 'as-needed'],
			'arrow-parens': ['off', 'always'],
			'arrow-spacing': ['off', {before: true, after: true}],
			'block-scoped-var': ['off'],
			'block-spacing': ['off', 'always'],
			'brace-style': ['off', '1tbs', {allowSingleLine: true}],
			camelcase: [
				'error',
				{
					properties: 'never',
					ignoreDestructuring: false,
					ignoreImports: false,
					ignoreGlobals: true,
				},
			],
			'capitalized-comments': [
				'off',
				'never',
				{
					line: {
						ignorePattern: '.*',
						ignoreInlineComments: true,
						ignoreConsecutiveComments: true,
					},
					block: {
						ignorePattern: '.*',
						ignoreInlineComments: true,
						ignoreConsecutiveComments: true,
					},
				},
			],
			'class-methods-use-this': [
				'error',
				{exceptMethods: [], enforceForClassFields: true},
			],
			'comma-dangle': [
				'off',
				{
					arrays: 'always-multiline',
					objects: 'always-multiline',
					imports: 'always-multiline',
					exports: 'always-multiline',
					functions: 'always-multiline',
				},
			],
			'comma-spacing': ['off', {before: false, after: true}],
			'comma-style': ['off', 'last'],
			complexity: ['error', 20],
			'computed-property-spacing': ['off', 'never'],
			'consistent-return': ['off'],
			'consistent-this': ['off', 'that'],
			'constructor-super': ['error'],
			curly: ['off', 'all'],
			'default-case': ['error', {commentPattern: '(?:)'}],
			'default-case-last': ['error'],
			'default-param-last': ['off'],
			'dot-location': ['error', 'property'],
			'dot-notation': ['off', {allowKeywords: true, allowPattern: ''}],
			'eol-last': ['error', 'always'],
			eqeqeq: ['error', 'smart'],
			'for-direction': ['error'],
			'func-call-spacing': ['off', 'never'],
			'func-name-matching': [
				'error',
				'never',
				{
					includeCommonJSModuleExports: false,
					considerPropertyDescriptor: true,
				},
			],
			'func-names': ['warn'],
			'func-style': ['error', 'expression', {allowArrowFunctions: true}],
			'function-call-argument-newline': ['off', 'consistent'],
			'function-paren-newline': ['off', 'consistent'],
			'generator-star-spacing': ['off', 'after'],
			'getter-return': ['error', {allowImplicit: true}],
			'grouped-accessor-pairs': ['error', 'getBeforeSet'],
			'guard-for-in': ['off'],
			'id-denylist': ['error', 'native'],
			'id-length': [
				'error',
				{
					min: 2,
					max: 30,
					properties: 'never',
					exceptions: ['_', 'i', 'j', 'k', 'x', 'y', 'z'],
				},
			],
			'id-match': ['off'],
			'implicit-arrow-linebreak': ['off', 'beside'],
			indent: [
				'off',
				2,
				{
					SwitchCase: 1,
					VariableDeclarator: 1,
					outerIIFEBody: 1,
					FunctionDeclaration: {
						parameters: 1,
						body: 1,
					},
					FunctionExpression: {
						parameters: 1,
						body: 1,
					},
					CallExpression: {
						arguments: 1,
					},
					ArrayExpression: 1,
					ObjectExpression: 1,
					ImportDeclaration: 1,
					flatTernaryExpressions: false,
					ignoredNodes: [
						'JSXElement',
						'JSXElement > *',
						'JSXAttribute',
						'JSXIdentifier',
						'JSXNamespacedName',
						'JSXMemberExpression',
						'JSXSpreadAttribute',
						'JSXExpressionContainer',
						'JSXOpeningElement',
						'JSXClosingElement',
						'JSXFragment',
						'JSXOpeningFragment',
						'JSXClosingFragment',
						'JSXText',
						'JSXEmptyExpression',
						'JSXSpreadChild',
					],
					ignoreComments: false,
					offsetTernaryExpressions: false,
				},
			],
			'init-declarations': ['off', 'always'],
			'key-spacing': ['off', {beforeColon: false, afterColon: true}],
			'keyword-spacing': ['off', {before: true, after: true, overrides: {}}],
			'line-comment-position': ['off', {position: 'above'}],
			'linebreak-style': ['off', 'unix'],
			'lines-around-comment': [
				'off',
				{
					beforeBlockComment: true,
					afterBlockComment: false,
					beforeLineComment: false,
					afterLineComment: false,
					allowBlockStart: false,
					allowBlockEnd: false,
				},
			],
			'lines-between-class-members': [
				'off',
				'always',
				{exceptAfterSingleLine: true},
			],
			'max-classes-per-file': ['off', 1],
			'max-depth': ['error', 4],
			'max-len': [
				'error',
				120,
				4,
				{
					ignoreUrls: true,
					ignoreComments: true,
					ignoreRegExpLiterals: true,
					ignoreStrings: true,
					ignoreTemplateLiterals: true,
				},
			],
			'max-lines': [
				'error',
				{max: 350, skipBlankLines: true, skipComments: true},
			],
			'max-lines-per-function': [
				'error',
				{max: 100, skipBlankLines: true, skipComments: true, IIFEs: true},
			],
			'max-nested-callbacks': ['error', 3],
			'max-params': ['error', 5],
			'max-statements': ['error', 30],
			'max-statements-per-line': ['error', {max: 1}],
			'multiline-comment-style': ['error', 'bare-block'],
			'multiline-ternary': ['off', 'always-multiline'],
			'new-cap': ['warn', {newIsCap: true, capIsNew: false, properties: true}],
			'new-parens': ['error'],
			'newline-per-chained-call': ['off', {ignoreChainWithDepth: 3}],
			'no-alert': ['error'],
			'no-array-constructor': ['error'],
			'no-async-promise-executor': ['error'],
			'no-await-in-loop': ['error'],
			'no-bitwise': ['off'],
			'no-caller': ['error'],
			'no-case-declarations': ['error'],
			'no-class-assign': ['error'],
			'no-compare-neg-zero': ['error'],
			'no-cond-assign': ['error', 'always'],
			'no-confusing-arrow': [
				'off',
				{allowParens: true, onlyOneSimpleParam: false},
			],
			'no-console': [
				'warn',
				{
					allow: ['error', 'info'],
				},
			],
			'no-const-assign': ['error'],
			'no-constant-condition': ['error', {checkLoops: false}],
			'no-constructor-return': ['error'],
			'no-continue': ['off'],
			'no-control-regex': ['error'],
			'no-debugger': ['error'],
			'no-delete-var': ['error'],
			'no-div-regex': ['error'],
			'no-dupe-args': ['error'],
			'no-dupe-class-members': ['error'],
			'no-dupe-else-if': ['error'],
			'no-dupe-keys': ['error'],
			'no-duplicate-case': ['error'],
			'no-duplicate-imports': ['off'],
			'no-else-return': ['error', {allowElseIf: false}],
			'no-empty': ['error', {allowEmptyCatch: true}],
			'no-empty-character-class': ['error'],
			'no-empty-function': ['error', {allow: ['arrowFunctions', 'functions']}],
			'no-empty-pattern': ['error'],
			'no-eq-null': ['off'],
			'no-eval': ['error'],
			'no-ex-assign': ['error'],
			'no-extend-native': ['error'],
			'no-extra-bind': ['error'],
			'no-extra-boolean-cast': ['error'],
			'no-extra-label': ['error'],
			'no-extra-parens': [
				'off',
				'all',
				{
					conditionalAssign: true,
					nestedBinaryExpressions: false,
					returnAssign: false,
					ignoreJSX: 'all',
					enforceForArrowConditionals: false,
				},
			],
			'no-extra-semi': ['error'],
			'no-fallthrough': ['error'],
			'no-floating-decimal': ['error'],
			'no-func-assign': ['error'],
			'no-global-assign': ['error', {exceptions: []}],
			'no-implicit-coercion': [
				'error',
				{
					boolean: false,
					number: true,
					string: true,
					disallowTemplateShorthand: false,
					allow: [],
				},
			],
			'no-implicit-globals': ['error'],
			'no-implied-eval': ['error'],
			'no-import-assign': ['error'],
			'no-inline-comments': ['off'],
			'no-inner-declarations': ['error', 'functions'],
			'no-invalid-regexp': ['error', {allowConstructorFlags: ['u', 'y']}],
			'no-invalid-this': ['error'],
			'no-irregular-whitespace': ['error'],
			'no-iterator': ['error'],
			'no-label-var': ['error'],
			'no-labels': ['error', {allowLoop: false, allowSwitch: false}],
			'no-lone-blocks': ['error'],
			'no-lonely-if': ['error'],
			'no-loop-func': ['error'],
			'no-loss-of-precision': ['error'],
			'no-magic-numbers': [
				'off',
				{
					ignore: [],
					ignoreArrayIndexes: true,
					enforceConst: true,
					detectObjects: false,
				},
			],
			'no-misleading-character-class': ['error'],
			'no-mixed-operators': [
				'error',
				{
					groups: [
						['%', '**'],
						['%', '+'],
						['%', '-'],
						['%', '*'],
						['%', '/'],
						['/', '*'],
						['&', '|', '<<', '>>', '>>>'],
						['==', '!=', '===', '!=='],
						['&&', '||'],
					],
					allowSamePrecedence: true,
				},
			],
			'no-mixed-spaces-and-tabs': ['off'],
			'no-multi-assign': ['error', {ignoreNonDeclaration: false}],
			'no-multi-spaces': ['error', {ignoreEOLComments: false}],
			'no-multi-str': ['error'],
			'no-multiple-empty-lines': ['error', {max: 1, maxEOF: 1}],
			'no-negated-condition': ['error'],
			'no-nested-ternary': ['off'],
			'no-new': ['error'],
			'no-new-func': ['error'],
			'no-new-object': ['error'],
			'no-new-symbol': ['error'],
			'no-new-wrappers': ['error'],
			'no-nonoctal-decimal-escape': ['error'],
			'no-obj-calls': ['error'],
			'no-octal': ['error'],
			'no-octal-escape': ['error'],
			'no-param-reassign': [
				'error',
				{
					props: true,
					ignorePropertyModificationsFor: [],
					ignorePropertyModificationsForRegex: [],
				},
			],
			'no-plusplus': ['error', {allowForLoopAfterthoughts: true}],
			'no-promise-executor-return': ['error'],
			'no-proto': ['error'],
			'no-prototype-builtins': ['error'],
			'no-redeclare': ['error'],
			'no-regex-spaces': ['error'],
			'no-restricted-exports': ['error', {restrictedNamedExports: ['then']}],
			'no-restricted-globals': [
				'off',
				{
					name: 'isFinite',
					message:
						'Use Number.isFinite instead https://github.com/airbnb/javascript#standard-library--isfinite',
				},
				{
					name: 'isNaN',
					message:
						'Use Number.isNaN instead https://github.com/airbnb/javascript#standard-library--isnan',
				},
				'addEventListener',
				'blur',
				'close',
				'closed',
				'confirm',
				'defaultStatus',
				'defaultstatus',
				'event',
				'external',
				'find',
				'focus',
				'frameElement',
				'frames',
				'history',
				'innerHeight',
				'innerWidth',
				'length',
				'location',
				'locationbar',
				'menubar',
				'moveBy',
				'moveTo',
				'name',
				'onblur',
				'onerror',
				'onfocus',
				'onload',
				'onresize',
				'onunload',
				'open',
				'opener',
				'opera',
				'outerHeight',
				'outerWidth',
				'pageXOffset',
				'pageYOffset',
				'parent',
				'print',
				'removeEventListener',
				'resizeBy',
				'resizeTo',
				'screen',
				'screenLeft',
				'screenTop',
				'screenX',
				'screenY',
				'scroll',
				'scrollbars',
				'scrollBy',
				'scrollTo',
				'scrollX',
				'scrollY',
				'self',
				'status',
				'statusbar',
				'stop',
				'toolbar',
				'top',
			],
			'no-restricted-imports': ['off', {paths: [], patterns: []}],
			'no-restricted-properties': [
				'error',
				{
					object: 'Symbol',
					property: 'for',
					message: 'Symbol.for is unshimmable',
				},
				{
					object: 'arguments',
					property: 'callee',
					message: 'arguments.callee is deprecated',
				},
				{
					property: '__defineGetter__',
					message: 'Please use Object.defineProperty instead.',
				},
				{
					property: '__defineSetter__',
					message: 'Please use Object.defineProperty instead.',
				},
			],
			'no-restricted-syntax': [
				'error',
				'DebuggerStatement',
				{
					selector: 'ForInStatement',
					message:
						'for..in loops iterate over the entire prototype chain, which is virtually never what you want. Use Object.{keys,values,entries}, and iterate over the resulting array.',
				},
				{
					selector: 'LabeledStatement',
					message:
						'Labels are a form of GOTO; using them makes code confusing and hard to maintain and understand.',
				},
				{
					selector: 'WithStatement',
					message:
						'`with` is disallowed in strict mode because it makes code impossible to predict and optimize.',
				},
				{
					selector: ':matches(ImportNamespaceSpecifier)',
					message: 'Import/export only modules you need',
				},
			],
			'no-return-assign': ['error', 'always'],
			'no-script-url': ['error'],
			'no-self-assign': ['error', {props: true}],
			'no-self-compare': ['off'],
			'no-sequences': ['error', {allowInParentheses: false}],
			'no-setter-return': ['error'],
			'no-shadow': ['off'],
			'no-shadow-restricted-names': ['error'],
			'no-sparse-arrays': ['error'],
			'no-tabs': ['off'],
			'no-template-curly-in-string': ['error'],
			'no-ternary': ['off'],
			'no-this-before-super': ['error'],
			'no-throw-literal': ['error'],
			'no-trailing-spaces': [
				'error',
				{skipBlankLines: false, ignoreComments: false},
			],
			'no-undef': ['off'],
			'no-undef-init': ['error'],
			'no-undefined': ['off'],
			'no-underscore-dangle': [
				'off',
				{
					allow: ['__REDUX_DEVTOOLS_EXTENSION_COMPOSE__'],
					allowAfterThis: false,
					allowAfterSuper: false,
					enforceInMethodNames: true,
					allowAfterThisConstructor: false,
					allowFunctionParams: true,
					enforceInClassFields: false,
				},
			],
			'no-unexpected-multiline': ['error'],
			'no-unmodified-loop-condition': ['error'],
			'no-unneeded-ternary': ['error', {defaultAssignment: false}],
			'no-unreachable': ['error'],
			'no-unreachable-loop': ['error', {ignore: []}],
			'no-unsafe-finally': ['error'],
			'no-unsafe-negation': ['error', {enforceForOrderingRelations: true}],
			'no-unsafe-optional-chaining': [
				'error',
				{disallowArithmeticOperators: true},
			],
			'no-unused-labels': ['error'],
			'no-unused-private-class-members': ['error'],
			'no-unused-vars': [
				'off',
				{vars: 'all', args: 'after-used', ignoreRestSiblings: true},
			],
			'no-use-before-define': ['off', 'nofunc'],
			'no-useless-backreference': ['error'],
			'no-useless-call': ['error'],
			'no-useless-catch': ['error'],
			'no-useless-computed-key': ['error', {enforceForClassMembers: true}],
			'no-useless-concat': ['error'],
			'no-useless-constructor': ['error'],
			'no-useless-escape': ['error'],
			'no-useless-rename': [
				'error',
				{
					ignoreDestructuring: false,
					ignoreImport: false,
					ignoreExport: false,
				},
			],
			'no-useless-return': ['error'],
			'no-var': ['off'],
			'no-void': ['off', {allowAsStatement: true}],
			'no-warning-comments': ['error', {terms: ['fixme']}],
			'no-whitespace-before-property': ['off'],
			'no-with': ['error'],
			'nonblock-statement-body-position': ['off', 'beside', {overrides: {}}],
			'object-curly-newline': [
				'off',
				{
					ObjectExpression: {
						minProperties: 4,
						multiline: true,
						consistent: true,
					},
					ObjectPattern: {
						minProperties: 4,
						multiline: true,
						consistent: true,
					},
					ImportDeclaration: {
						minProperties: 4,
						multiline: true,
						consistent: true,
					},
					ExportDeclaration: {
						minProperties: 4,
						multiline: true,
						consistent: true,
					},
				},
			],
			'object-curly-spacing': ['off', 'never'],
			'object-property-newline': [
				'off',
				{
					allowAllPropertiesOnSameLine: true,
					allowMultiplePropertiesPerLine: false,
				},
			],
			'object-shorthand': ['error', 'always'],
			'one-var': ['off', 'never'],
			'one-var-declaration-per-line': ['error', 'initializations'],
			'operator-assignment': ['off', 'always'],
			'operator-linebreak': [
				'off',
				'after',
				{
					overrides: {
						'?': 'before',
						':': 'before',
					},
				},
			],
			'padded-blocks': [
				'off',
				{blocks: 'never', classes: 'never', switches: 'never'},
				{allowSingleLineBlocks: true},
			],
			'padding-line-between-statements': [
				'off',
				{blankLine: 'always', prev: 'directive', next: '*'},
				{blankLine: 'any', prev: 'directive', next: 'directive'},
			],
			'prefer-arrow-callback': [
				'error',
				{allowNamedFunctions: true, allowUnboundThis: true},
			],
			'prefer-const': [
				'off',
				{destructuring: 'any', ignoreReadBeforeAssign: true},
			],
			'prefer-destructuring': [
				'off',
				{
					VariableDeclarator: {
						array: false,
						object: true,
					},
					AssignmentExpression: {
						array: true,
						object: true,
					},
				},
				{enforceForRenamedProperties: false},
			],
			'prefer-exponentiation-operator': ['off'],
			'prefer-named-capture-group': ['off'],
			'prefer-numeric-literals': ['off'],
			'prefer-object-has-own': ['off'],
			'prefer-object-spread': ['off'],
			'prefer-promise-reject-errors': ['error', {allowEmptyReject: true}],
			'prefer-regex-literals': ['error', {disallowRedundantWrapping: true}],
			'prefer-rest-params': ['off'],
			'prefer-spread': ['off'],
			'prefer-template': ['off'],
			'quote-props': ['error', 'as-needed', {keywords: true}],
			quotes: ['error', 'single', 'avoid-escape'],
			radix: ['error'],
			'require-atomic-updates': ['error', {allowProperties: true}],
			'require-await': ['error'],
			'require-unicode-regexp': ['off'],
			'require-yield': ['error'],
			'rest-spread-spacing': ['error', 'never'],
			semi: ['error', 'always'],
			'semi-spacing': ['error', {before: false, after: true}],
			'semi-style': ['error', 'last'],
			'sort-imports': [
				'off',
				{
					ignoreCase: false,
					ignoreDeclarationSort: false,
					ignoreMemberSort: false,
					memberSyntaxSortOrder: [Array],
				},
			],
			'sort-keys': ['off', 'asc', {caseSensitive: false, natural: true}],
			'sort-vars': ['off'],
			'space-before-blocks': ['off', 'always'],
			'space-before-function-paren': [
				'off',
				{anonymous: 'never', named: 'never', asyncArrow: 'always'},
			],
			'space-in-parens': ['off', 'never'],
			'space-infix-ops': ['off'],
			'space-unary-ops': ['off', {words: true, nonwords: false}],
			'spaced-comment': [
				'error',
				'always',
				{
					markers: ['='],
				},
			],
			strict: ['error', 'global'],
			'switch-colon-spacing': ['off', {after: true, before: false}],
			'symbol-description': ['error'],
			'template-curly-spacing': ['off', 'never'],
			'template-tag-spacing': ['off', 'never'],
			'unicode-bom': ['error', 'never'],
			'use-isnan': [
				'error',
				{enforceForSwitchCase: true, enforceForIndexOf: false},
			],
			'valid-typeof': ['error', {requireStringLiterals: true}],
			'vars-on-top': ['off'],
			'wrap-iife': ['error', 'outside', {functionPrototypeMethods: true}],
			'wrap-regex': ['off'],
			'yield-star-spacing': ['off', {before: false, after: true}],
			yoda: ['error', 'never', {exceptRange: true, onlyEquality: false}],
		},
	},
];
