import type {Linter} from 'eslint';
import unicornPlugin from 'eslint-plugin-unicorn';
import {FILES} from '../constants.js';

export const unicornConfig: Linter.FlatConfig[] = [
	{
		files: FILES,
		plugins: {unicorn: unicornPlugin},
		rules: {
			'unicorn/better-regex': ['error', {sortCharacterClasses: false}],
			'unicorn/catch-error-name': ['error'],
			'unicorn/consistent-destructuring': ['off'],
			'unicorn/consistent-function-scoping': ['off'],
			'unicorn/custom-error-definition': ['off'],
			'unicorn/empty-brace-spaces': ['off'],
			'unicorn/error-message': ['error'],
			'unicorn/escape-case': ['error'],
			'unicorn/expiring-todo-comments': ['error'],
			'unicorn/explicit-length-check': ['error'],
			'unicorn/filename-case': ['warn'],
			'unicorn/import-style': ['error'],
			'unicorn/new-for-builtins': ['error'],
			'unicorn/no-abusive-eslint-disable': ['error'],
			'unicorn/no-array-callback-reference': ['off'],
			'unicorn/no-array-for-each': ['warn'],
			'unicorn/no-array-method-this-argument': ['off'],
			'unicorn/no-array-push-push': ['error'],
			'unicorn/no-array-reduce': ['off'],
			'unicorn/no-await-expression-member': ['error'],
			'unicorn/no-console-spaces': ['error'],
			'unicorn/no-document-cookie': ['error'],
			'unicorn/no-empty-file': ['error'],
			'unicorn/no-for-loop': ['error'],
			'unicorn/no-hex-escape': ['error'],
			'unicorn/no-instanceof-array': ['error'],
			'unicorn/no-invalid-remove-event-listener': ['error'],
			'unicorn/no-keyword-prefix': ['off'],
			'unicorn/no-lonely-if': ['error'],
			'unicorn/no-negated-condition': 'off',
			'unicorn/no-nested-ternary': ['off'],
			'unicorn/no-new-array': ['warn'],
			'unicorn/no-new-buffer': ['error'],
			'unicorn/no-null': ['off'],
			'unicorn/no-object-as-default-parameter': ['error'],
			'unicorn/no-process-exit': ['error'],
			'unicorn/no-static-only-class': ['error'],
			'unicorn/no-thenable': ['off'],
			'unicorn/no-this-assignment': ['error'],
			'unicorn/no-typeof-undefined': 'off',
			'unicorn/no-unnecessary-await': ['error'],
			'unicorn/no-unreadable-array-destructuring': ['error'],
			'unicorn/no-unreadable-iife': ['error'],
			'unicorn/no-unused-properties': ['off'],
			'unicorn/no-useless-fallback-in-spread': ['error'],
			'unicorn/no-useless-length-check': ['error'],
			'unicorn/no-useless-promise-resolve-reject': ['error'],
			'unicorn/no-useless-spread': ['error'],
			'unicorn/no-useless-switch-case': ['error'],
			'unicorn/no-useless-undefined': ['off'],
			'unicorn/no-zero-fractions': ['error'],
			'unicorn/number-literal-case': ['off'],
			'unicorn/numeric-separators-style': ['error'],
			'unicorn/prefer-add-event-listener': ['error'],
			'unicorn/prefer-array-find': ['error'],
			'unicorn/prefer-array-flat': ['error'],
			'unicorn/prefer-array-flat-map': ['error'],
			'unicorn/prefer-array-index-of': ['error'],
			'unicorn/prefer-array-some': ['error'],
			'unicorn/prefer-at': ['off'],
			'unicorn/prefer-blob-reading-methods': 'off',
			'unicorn/prefer-code-point': ['error'],
			'unicorn/prefer-date-now': ['error'],
			'unicorn/prefer-default-parameters': ['error'],
			'unicorn/prefer-dom-node-append': ['error'],
			'unicorn/prefer-dom-node-dataset': ['error'],
			'unicorn/prefer-dom-node-remove': ['error'],
			'unicorn/prefer-dom-node-text-content': ['error'],
			'unicorn/prefer-event-target': ['off'],
			'unicorn/prefer-export-from': ['error'],
			'unicorn/prefer-includes': ['error'],
			'unicorn/prefer-json-parse-buffer': ['off'],
			'unicorn/prefer-keyboard-event-key': ['error'],
			'unicorn/prefer-logical-operator-over-ternary': ['error'],
			'unicorn/prefer-math-trunc': ['error'],
			'unicorn/prefer-modern-dom-apis': ['error'],
			'unicorn/prefer-modern-math-apis': ['error'],
			'unicorn/prefer-module': ['off'],
			'unicorn/prefer-native-coercion-functions': ['off'],
			'unicorn/prefer-negative-index': ['error'],
			'unicorn/prefer-node-protocol': ['off'],
			'unicorn/prefer-number-properties': ['error'],
			'unicorn/prefer-object-from-entries': ['error'],
			'unicorn/prefer-optional-catch-binding': ['error'],
			'unicorn/prefer-prototype-methods': ['error'],
			'unicorn/prefer-query-selector': ['error'],
			'unicorn/prefer-reflect-apply': ['error'],
			'unicorn/prefer-regexp-test': ['error'],
			'unicorn/prefer-set-has': ['error'],
			'unicorn/prefer-set-size': 'off',
			'unicorn/prefer-spread': ['error'],
			'unicorn/prefer-string-replace-all': ['off'],
			'unicorn/prefer-string-slice': ['error'],
			'unicorn/prefer-string-starts-ends-with': ['error'],
			'unicorn/prefer-string-trim-start-end': ['error'],
			'unicorn/prefer-switch': ['error'],
			'unicorn/prefer-ternary': ['error', 'only-single-line'],
			'unicorn/prefer-top-level-await': ['off'],
			'unicorn/prefer-type-error': ['error'],
			'unicorn/prevent-abbreviations': ['off'],
			'unicorn/relative-url-style': ['error'],
			'unicorn/require-array-join-separator': ['error'],
			'unicorn/require-number-to-fixed-digits-argument': ['error'],
			'unicorn/require-post-message-target-origin': ['off'],
			'unicorn/string-content': ['off'],
			'unicorn/switch-case-braces': ['error'],
			'unicorn/template-indent': ['warn', {indent: '\t'}],
			'unicorn/text-encoding-identifier-case': ['error'],
			'unicorn/throw-new-error': ['error'],
		},
	},
];
