/* eslint-disable no-restricted-syntax */
import * as _configPrettier from 'eslint-config-prettier';
import * as _pluginAntfu from 'eslint-plugin-antfu';
import * as _pluginComments from 'eslint-plugin-eslint-comments';
import * as _pluginImport from 'eslint-plugin-i';
import * as _pluginJsonc from 'eslint-plugin-jsonc';
import * as _pluginMarkdown from 'eslint-plugin-markdown';
import * as _pluginPrettier from 'eslint-plugin-prettier';
import * as _pluginSortKeys from 'eslint-plugin-sort-keys';
import * as _pluginTypeScript from '@typescript-eslint/eslint-plugin';
import * as _pluginUnicorn from 'eslint-plugin-unicorn';
import * as _pluginUnusedImports from 'eslint-plugin-unused-imports';
import * as _pluginYml from 'eslint-plugin-yml';
import * as _pluginReactHooks from 'eslint-plugin-react-hooks';
import * as _pluginReact from 'eslint-plugin-react';
import * as _pluginA11y from 'eslint-plugin-jsx-a11y';
import * as _pluginNextjs from '@next/eslint-plugin-next';
import * as _parserJsonc from 'jsonc-eslint-parser';
import * as _parserYml from 'yaml-eslint-parser';
import * as _parserTypeScript from '@typescript-eslint/parser';
import * as _pluginNode from 'eslint-plugin-n';
import * as _pluginTailwindcss from 'eslint-plugin-tailwindcss';
import * as _pluginPromise from 'eslint-plugin-promise';
import * as _pluginStylistic from '@stylistic/eslint-plugin';

const interopDefault = (mod: any): any => {
	return mod.default || mod;
};

export const configPrettier = interopDefault(_configPrettier);
export const pluginAntfu = interopDefault(_pluginAntfu);
export const pluginComments = interopDefault(_pluginComments);
export const pluginImport = interopDefault(_pluginImport);
export const pluginJsonc = interopDefault(_pluginJsonc);
export const pluginMarkdown = interopDefault(_pluginMarkdown);
export const pluginPrettier = interopDefault(_pluginPrettier);
export const pluginSortKeys = interopDefault(_pluginSortKeys);
export const pluginTypeScript = interopDefault(_pluginTypeScript);
export const pluginUnicorn = interopDefault(_pluginUnicorn);
export const pluginUnusedImports = interopDefault(_pluginUnusedImports);
export const pluginYml = interopDefault(_pluginYml);
export const pluginPromise = interopDefault(_pluginPromise);
export const pluginReactHooks = interopDefault(_pluginReactHooks);
export const pluginReact = interopDefault(_pluginReact);
export const pluginA11y = interopDefault(_pluginA11y);
export const pluginNextjs = interopDefault(_pluginNextjs);
export const pluginNode = interopDefault(_pluginNode);
export const parserJsonc = interopDefault(_parserJsonc);
export const parserYml = interopDefault(_parserYml);
export const parserTypeScript = interopDefault(_parserTypeScript);
export const pluginTailwindcss = interopDefault(_pluginTailwindcss);
export const pluginStylistic = interopDefault(_pluginStylistic);
